[package]
name = "nagomi-worker"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
portable-pty = "0.8"
nagomi-protocol = { path = "../nagomi-protocol" }

[[bin]]
name = "nagomi-worker"
path = "src/main.rs"
